"""product_assets inline storage + upload route

Revision ID: efe5f7fce06a
Revises: a268bdef26b9
Create Date: 2025-08-11 18:25:56.935239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efe5f7fce06a'
down_revision: Union[str, Sequence[str], None] = 'a268bdef26b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_assets', sa.Column('filename', sa.String(length=255), nullable=True))
    op.add_column('product_assets', sa.Column('content_type', sa.String(length=100), nullable=True))
    op.add_column('product_assets', sa.Column('size', sa.BigInteger(), nullable=True))
    op.add_column('product_assets', sa.Column('sha256', sa.String(length=64), nullable=True))
    op.add_column('product_assets', sa.Column('data', sa.LargeBinary(), nullable=True))
    op.alter_column('product_assets', 'uri',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    op.create_index(op.f('ix_product_assets_sha256'), 'product_assets', ['sha256'], unique=False)
    op.create_foreign_key(None, 'user_roles', 'roles', ['role_id'], ['role_id'])
    op.create_foreign_key(None, 'user_roles', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_index(op.f('ix_product_assets_sha256'), table_name='product_assets')
    op.alter_column('product_assets', 'uri',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
    op.drop_column('product_assets', 'data')
    op.drop_column('product_assets', 'sha256')
    op.drop_column('product_assets', 'size')
    op.drop_column('product_assets', 'content_type')
    op.drop_column('product_assets', 'filename')
    # ### end Alembic commands ###
